# Validate the data

In [174]:
import pandas as pd

In [175]:
# import the users
user= pd.read_csv('user.csv')
user.head()

   Unnamed: 0  userID                          userName
0           0       1  f4b46be21c2f553811cc8a73c4f0ff05
1           1       2  2ced3734cc9c164edd9a8f5fbebe976f
2           2       3  c84c4ea8ba67211f84781bdd64cafe43
3           3       4  1776d1765f5e82cd660d8d502f227402
4           4       5  4e8c2c300d96929895ce0edba915af16

In [176]:
userUser= pd.read_csv('userUser.csv')
userUser.head()

   Unnamed: 0  Follower  Followee
0           0       507         1
1           1      1589         1
2           2      5307         1
3           3     11421         1
4           4     13267         1

In [177]:
test = pd.DataFrame()
test["a"] = ["a", "B", "C"]
test

   a
0  a
1  B
2  C

In [178]:
# import re
# ds = re.search(r"'published_time': '(.*)'},", newsWithContent.loc[0,"meta_data"]).group(1)

In [179]:
newsWithContent= pd.read_csv('newsWithContent.csv')
newsWithContent.head()

,Unnamed: 0,newsID,newsName,Fake,top_img,text,authors,keywords,meta_data,canonical_link,images,title,url,summary,movies,publish_date,source
0,0,1,PolitiFact_Real_1,False,http://occupydemocrats.com/wp-content/uploads/...,16.8k SHARES SHARE THIS STORY\n\nHillary Clint...,"['Brett Bose', 'Grant Stern', 'Steve Bernstein...",[],{'generator': 'Powered by Visual Composer - dr...,http://occupydemocrats.com/2016/09/27/trump-ju...,['http://occupydemocrats.com/wp-content/upload...,Trump Just Insulted Millions Who Lost Everythi...,http://occupydemocrats.com/2016/09/27/trump-ju...,NaN,[],{'$date': 1474934400000},http://occupydemocrats.com
1,1,2,PolitiFact_Real_2,False,http://occupydemocrats.com/wp-content/uploads/...,24.8k SHARES SHARE THIS STORY\n\nRepublican no...,"['Colin Taylor', 'Grant Stern', 'Brett Bose', ...",[],{'generator': 'Powered by Visual Composer - dr...,http://occupydemocrats.com/2016/09/22/unhinged...,['http://occupydemocrats.com/wp-content/upload...,Trump Campaign Chair Says Racism Didn't Exist ...,http://occupydemocrats.com/2016/09/22/unhinged...,NaN,[],{'$date': 1474502400000},http://occupydemocrats.com
2,2,3,PolitiFact_Real_3,False,NaN,The University of North Dakota is investigatin...,NaN,NaN,NaN,NaN,NaN,'Locked the black bitch out': White students u...,NaN,NaN,NaN,NaN,NaN
3,3,4,PolitiFact_Real_4,False,http://occupydemocrats.com/wp-content/uploads/...,12k SHARES SHARE THIS STORY\n\nMassive protest...,"['Colin Taylor', 'Grant Stern', 'Brett Bose', ...",[],{'generator': 'Powered by Visual Composer - dr...,http://occupydemocrats.com/2016/09/21/massive-...,['http://occupydemocrats.com/wp-content/upload...,Massive Protests Erupt In North Carolina After...,http://occupydemocrats.com/2016/09/21/massive-...,NaN,[],{'$date': 1474416000000},http://occupydemocrats.com
4,4,5,PolitiFact_Real_5,False,http://addictinginfo.addictinginfoent.netdna-c...,"In the first half of the debate, Donald Trump ...",['Ryan Denson'],[],{'publisher': 'Addicting Info | The Knowledge ...,http://addictinginfo.com/2016/09/27/howard-dea...,"['http://i.imgur.com/JeqZLhj.png', 'https://d5...",Howard Dean ROASTS Trump Over Debate Sniffles:...,http://addictinginfo.org/2016/09/27/howard-dea...,NaN,[],{'$date': 1474934400000},http://addictinginfo.org

In [180]:
newsWithContent.shape

(240, 17)

In [181]:
newsUserGroupped= pd.read_csv('newsUserGroupped.csv')
newsUserGroupped.head()

   newsID  userID  PostIterations
0       1     105               1
1       1    1027               1
2       1    1592               1
3       1    2486               1
4       1    2787               1

In [182]:
newsUserGroupped.groupby(['userID','newsID'])['PostIterations'].count().reset_index()

       userID  newsID  PostIterations
0           1     240               1
1           2     124               1
2           3     162               1
3           4     233               1
4           5      50               1
...       ...     ...             ...
32786   23861     227               1
32787   23862     155               1
32788   23863     227               1
32789   23864     147               1
32790   23865     204               1

[32791 rows x 3 columns]

In [183]:
newsUserGroupped.shape

(32791, 3)

## Let's Merge

### 1. User Data -> Followers and Followee for Each user

#### 1.1 Followers for a user

In [184]:
followers_df= userUser.groupby('Followee')['Follower'].count().reset_index()
followers_df.columns= ['userID', 'No. of Followers']
followers_df.head()

   userID  No. of Followers
0       1                 6
1       2                11
2       3                48
3       4                24
4       5                18

In [185]:
followers_df.shape

(22776, 2)

#### 1.2 Followees for a user

In [186]:
followees_df= userUser.groupby('Follower')['Followee'].count().reset_index()
followees_df.columns= ['userID', 'No. of Followees']
followees_df.head()

   userID  No. of Followees
0       1                 5
1       3                25
2       4                17
3       5               230
4       7                 3

In [187]:
user

       Unnamed: 0  userID                          userName
0               0       1  f4b46be21c2f553811cc8a73c4f0ff05
1               1       2  2ced3734cc9c164edd9a8f5fbebe976f
2               2       3  c84c4ea8ba67211f84781bdd64cafe43
3               3       4  1776d1765f5e82cd660d8d502f227402
4               4       5  4e8c2c300d96929895ce0edba915af16
...           ...     ...                               ...
23860       23860   23861  b305de06bbde74882617c7371a016902
23861       23861   23862  349724def708557e00d02f4e22a72cfa
23862       23862   23863  d98ce466aaf87b257c17e7e94baafac3
23863       23863   23864  814cf5bbe8eb8e9fed59c2f423b0201a
23864       23864   23865  260f0769a03173b7111b8139522b7845

[23865 rows x 3 columns]

#### 1.3 Merge with followers_df

In [188]:
users_info_0= user.merge(followers_df, how='left', on ='userID')
users_info_0

       Unnamed: 0  userID                          userName  No. of Followers
0               0       1  f4b46be21c2f553811cc8a73c4f0ff05               6.0
1               1       2  2ced3734cc9c164edd9a8f5fbebe976f              11.0
2               2       3  c84c4ea8ba67211f84781bdd64cafe43              48.0
3               3       4  1776d1765f5e82cd660d8d502f227402              24.0
4               4       5  4e8c2c300d96929895ce0edba915af16              18.0
...           ...     ...                               ...               ...
23860       23860   23861  b305de06bbde74882617c7371a016902               3.0
23861       23861   23862  349724def708557e00d02f4e22a72cfa               3.0
23862       23862   23863  d98ce466aaf87b257c17e7e94baafac3               4.0
23863       23863   23864  814cf5bbe8eb8e9fed59c2f423b0201a               4.0
23864       23864   23865  260f0769a03173b7111b8139522b7845               4.0

[23865 rows x 4 columns]

#### 1.4 Merge with followees_df

In [189]:
users_info = users_info_0.merge(followees_df, how='left', on ='userID')
users_info['No. of Followers'].fillna(0, inplace = True)
users_info['No. of Followees'].fillna(0, inplace = True)
users_info.drop(columns= ['Unnamed: 0', 'userName'], inplace = True)
users_info

       userID  No. of Followers  No. of Followees
0           1               6.0               5.0
1           2              11.0               0.0
2           3              48.0              25.0
3           4              24.0              17.0
4           5              18.0             230.0
...       ...               ...               ...
23860   23861               3.0               5.0
23861   23862               3.0               0.0
23862   23863               4.0               5.0
23863   23864               4.0               0.0
23864   23865               4.0               2.0

[23865 rows x 3 columns]

## 2. Merge User info & news info

### 2.1 Merge with newsID and postIterations

In [190]:
userNewsInfo_0= users_info.merge(newsUserGroupped, how='right', on ='userID')
userNewsInfo_0

       userID  No. of Followers  No. of Followees  newsID  PostIterations
0           1               6.0               5.0     240               1
1           2              11.0               0.0     124               1
2           3              48.0              25.0     162               1
3           4              24.0              17.0     233               1
4           5              18.0             230.0      50               1
...       ...               ...               ...     ...             ...
32786   23861               3.0               5.0     227               1
32787   23862               3.0               0.0     155               1
32788   23863               4.0               5.0     227               1
32789   23864               4.0               0.0     147               1
32790   23865               4.0               2.0     204               1

[32791 rows x 5 columns]

### 2.2 Merge with new Content

In [191]:
userNewsInfo= userNewsInfo_0.merge(newsWithContent, how='left', on ='newsID')
newsWithContent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      240 non-null    int64
 1   newsID          240 non-null    int64
 2   newsName        240 non-null    object
 3   Fake            240 non-null    bool
 4   top_img         208 non-null    object
 5   text            238 non-null    object
 6   authors         209 non-null    object
 7   keywords        209 non-null    object
 8   meta_data       209 non-null    object
 9   canonical_link  204 non-null    object
 10  images          209 non-null    object
 11  title           240 non-null    object
 12  url             209 non-null    object
 13  summary         0 non-null      float64
 14  movies          209 non-null    object
 15  publish_date    164 non-null    object
 16  source          209 non-null    object
dtypes: bool(1), float64(1), int64(2), object(13)
memory usage: 30.4+ KB

In [192]:
groupped= userNewsInfo.groupby(['newsID']).agg({'No. of Followers':'mean', 'No. of Followees':'mean','PostIterations': 'sum', 'userID':'count'}).reset_index()
groupped

     newsID  No. of Followers  No. of Followees  PostIterations  userID
0         1         60.085714         97.914286              35      35
1         2         27.936170         21.446809              47      47
2         3         36.812500         31.843750              32      32
3         4         18.526316         11.684211              19      19
4         5         22.285714         19.857143               7       7
..      ...               ...               ...             ...     ...
235     236         26.783133         27.421687              83      83
236     237         23.714286         17.142857               7       7
237     238         26.241379         25.448276              29      29
238     239          6.142857          1.000000               7       7
239     240         31.436893         25.543689             103     103

[240 rows x 5 columns]

In [203]:
newsUserContent= newsWithContent.merge(groupped , on= 'newsID', how = 'inner')
newsUserContent.rename(columns= {'No. of Followers': 'avg No. of Followers','No. of Followees': 'avg No. of Followees', 'userID':'Unique User count' }, inplace = True)
newsUserContent['shares/user']= newsUserContent['PostIterations']/ newsUserContent['Unique User count']
# for ind in newsUserContent.index :
#     newsUserContent['countImages'][ind] = str(newsUserContent['images'][ind]).count(',')+1
#     newsUserContent['countAuthors'][ind] = str(newsUserContent['authors'][ind]).count(',')+1
#     newsUserContent['countKeywords'][ind] = str(newsUserContent['keywords'][ind]).count(',')+1
    
newsUserContent.head(2)

,Unnamed: 0,newsID,newsName,Fake,top_img,text,authors,keywords,meta_data,canonical_link,...,url,summary,movies,publish_date,source,avg No. of Followers,avg No. of Followees,PostIterations,Unique User count,shares/user
0,0,1,PolitiFact_Real_1,False,http://occupydemocrats.com/wp-content/uploads/...,16.8k SHARES SHARE THIS STORY\n\nHillary Clint...,"['Brett Bose', 'Grant Stern', 'Steve Bernstein...",[],{'generator': 'Powered by Visual Composer - dr...,http://occupydemocrats.com/2016/09/27/trump-ju...,...,http://occupydemocrats.com/2016/09/27/trump-ju...,NaN,[],{'$date': 1474934400000},http://occupydemocrats.com,60.085714,97.914286,35,35,1.0
1,1,2,PolitiFact_Real_2,False,http://occupydemocrats.com/wp-content/uploads/...,24.8k SHARES SHARE THIS STORY\n\nRepublican no...,"['Colin Taylor', 'Grant Stern', 'Brett Bose', ...",[],{'generator': 'Powered by Visual Composer - dr...,http://occupydemocrats.com/2016/09/22/unhinged...,...,http://occupydemocrats.com/2016/09/22/unhinged...,NaN,[],{'$date': 1474502400000},http://occupydemocrats.com,27.936170,21.446809,47,47,1.0

In [204]:
## This snippet will add the count columns for images, authors, and keywords.

newsUserContent.loc[newsUserContent["images"].isna(), "images"] = "[]"
newsUserContent.loc[newsUserContent["authors"].isna(), "authors"] = "[]"
newsUserContent.loc[newsUserContent["keywords"].isna(), "keywords"] = "[]"

newsUserContent['countImages'] = newsUserContent.apply(lambda x: len(eval(x["images"])), axis=1)
newsUserContent['countAuthors'] = newsUserContent.apply(lambda x: len(eval(x["authors"])), axis=1)
newsUserContent['countKeywords'] = newsUserContent.apply(lambda x: len(eval(x["keywords"])), axis=1)

newsUserContent
## End snippet

,Unnamed: 0,newsID,newsName,Fake,top_img,text,authors,keywords,meta_data,canonical_link,...,publish_date,source,avg No. of Followers,avg No. of Followees,PostIterations,Unique User count,shares/user,countImages,countAuthors,countKeywords
0,0,1,PolitiFact_Real_1,False,http://occupydemocrats.com/wp-content/uploads/...,16.8k SHARES SHARE THIS STORY\n\nHillary Clint...,"['Brett Bose', 'Grant Stern', 'Steve Bernstein...",[],{'generator': 'Powered by Visual Composer - dr...,http://occupydemocrats.com/2016/09/27/trump-ju...,...,{'$date': 1474934400000},http://occupydemocrats.com,60.085714,97.914286,35,35,1.0,16,4,0
1,1,2,PolitiFact_Real_2,False,http://occupydemocrats.com/wp-content/uploads/...,24.8k SHARES SHARE THIS STORY\n\nRepublican no...,"['Colin Taylor', 'Grant Stern', 'Brett Bose', ...",[],{'generator': 'Powered by Visual Composer - dr...,http://occupydemocrats.com/2016/09/22/unhinged...,...,{'$date': 1474502400000},http://occupydemocrats.com,27.936170,21.446809,47,47,1.0,16,4,0
2,2,3,PolitiFact_Real_3,False,NaN,The University of North Dakota is investigatin...,[],[],NaN,NaN,...,NaN,NaN,36.812500,31.843750,32,32,1.0,0,0,0
3,3,4,PolitiFact_Real_4,False,http://occupydemocrats.com/wp-content/uploads/...,12k SHARES SHARE THIS STORY\n\nMassive protest...,"['Colin Taylor', 'Grant Stern', 'Brett Bose', ...",[],{'generator': 'Powered by Visual Composer - dr...,http://occupydemocrats.com/2016/09/21/massive-...,...,{'$date': 1474416000000},http://occupydemocrats.com,18.526316,11.684211,19,19,1.0,16,4,0
4,4,5,PolitiFact_Real_5,False,http://addictinginfo.addictinginfoent.netdna-c...,"In the first half of the debate, Donald Trump ...",['Ryan Denson'],[],{'publisher': 'Addicting Info | The Knowledge ...,http://addictinginfo.com/2016/09/27/howard-dea...,...,{'$date': 1474934400000},http://addictinginfo.org,22.285714,19.857143,7,7,1.0,9,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,235,236,PolitiFact_Fake_116,True,http://redherald.com/wp-content/uploads/2017/0...,Gretchen Carlson is renewing her push for an A...,[],[],"{'generator': 'WordPress 4.8.1', 'og': {'site_...",http://redherald.com/gretchen-carlson-2nd-amen...,...,{'$date': 1498587832000},http://redherald.com,26.783133,27.421687,83,83,1.0,1,0,0
236,236,237,PolitiFact_Fake_117,True,http://conservativearmy88.com/wp-content/uploa...,Many Hollywood celebrities announced that they...,[],[],{'description': 'Many Hollywood celebrities an...,http://conservativearmy88.com/breaking-hollywo...,...,{'$date': 1500057441000},http://conservativearmy88.com,23.714286,17.142857,7,7,1.0,9,0,0
237,237,238,PolitiFact_Fake_118,True,http://breaking.newsfeedhunter.com/wp-content/...,"Well, well, well…it looks like Obummer wasn’t ...",[],[],"{'description': 'Well, well, well…it looks lik...",http://breaking.newsfeedhunter.com/russian-man...,...,{'$date': 1499900339000},http://breaking.newsfeedhunter.com,26.241379,25.448276,29,29,1.0,19,0,0
238,238,239,PolitiFact_Fake_119,True,http://dailythings.world/wp-content/uploads/20...,Barack Obama is a sick human being unfit for a...,['Please Enter Your Name Here'],[],"{'generator': 'WordPress 4.8.1', 'author': 'ad...",http://dailythings.world/2017/07/20/barack-oba...,...,{'$date': 1500508800000},http://dailythings.world,6.142857,1.000000,7,7,1.0,12,1,0
239,239,240,PolitiFact_Fake_120,True,http://usadailynews24.com/wp-content/uploads/2...,The biggest story this week was the arrest of ...,[],[],{'description': 'The biggest story this week w...,http://usadailynews24.com/wasserman-schultz-go...,...,{'$date': 1501283964000},http://usadailynews24.com,31.436893,25.543689,103,103,1.0,4,0,0

In [106]:
newsUserContent[newsUserContent["publish_date"].isna()] = ""
newsUserContent.apply(lambda r: type(r["publish_date"]), axis=1).unique()

array([<class 'str'>], dtype=object)

In [103]:
newsUserContent.apply(lambda r: re.search("\d*", r["publish_date"]) , axis=1)

TypeError: expected string or bytes-like object

In [222]:
n2.publish_date[0]

"{'$date': 1474934400000}"

In [224]:
re.search(r"'$date':'(\d*)", "{'$date': 1474934400000}").group(0)

AttributeError: 'NoneType' object has no attribute 'group'

In [212]:
n2 = newsUserContent.copy()
n2[n2["publish_date"].isna()] =  "{'$date': 0000000000000}"

n2.apply(lambda r: re.search(r"(\d*)", r["publish_date"]).group(1) , axis=1)

0
1
2
3
4
      ..
235
236
237
238
239
Length: 240, dtype: object

In [167]:



newsUserContent[newsUserContent.apply(lambda r: re.search(r"'published_time': '(.*)'},", r['meta_data']), axis=1).isna()]

,Unnamed: 0,newsID,newsName,Fake,top_img,text,authors,keywords,meta_data,canonical_link,...,publish_date,source,avg No. of Followers,avg No. of Followees,PostIterations,Unique User count,shares/user,countImages,countAuthors,countKeywords
2,[],[],[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],0,0,0
4,4,5,PolitiFact_Real_5,False,http://addictinginfo.addictinginfoent.netdna-c...,"In the first half of the debate, Donald Trump ...",['Ryan Denson'],[],{'publisher': 'Addicting Info | The Knowledge ...,http://addictinginfo.com/2016/09/27/howard-dea...,...,{'$date': 1474934400000},http://addictinginfo.org,22.2857,19.8571,7,7,1,9,1,1
6,6,7,PolitiFact_Real_7,False,http://addictinginfo.addictinginfoent.netdna-c...,If you want to watch a conservative throw a te...,['Stephen D Foster Jr'],[],{'publisher': 'Addicting Info | The Knowledge ...,http://addictinginfo.com/2016/09/23/conservati...,...,{'$date': 1474588800000},http://author.addictinginfo.org,17.7857,15.5714,14,14,1,9,1,1
10,10,11,PolitiFact_Real_11,False,http://v.politico.com/images/1155968404/201609...,Trump: 'I was going to say something extremely...,"['Ben Schreckinger', 'Maggie Severns', 'Jack S...",[],"{'description': ""&quot;I said to myself, I can...",http://www.politico.com/story/2016/09/what-was...,...,{'$date': 1474931249000},http://politi.co,32.9688,28.0312,32,32,1,2,3,3
11,11,12,PolitiFact_Real_12,False,http://static.politico.com/4f/d1/2a153a1445ca8...,Donald Trump mocked Hillary Clinton's planes a...,"['Jack Shafer', 'Nolan D']",[],{'description': '“Hillary Clinton is taking th...,http://www.politico.com/story/2016/09/trump-cl...,...,{'$date': 1474368432000},http://politi.co,17.9318,11.3864,44,44,1,3,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,217,PolitiFact_Fake_97,True,http://themiamigazette.com/wp-content/uploads/...,"Police in Vernal Heights, Florida, arrested 3-...",['Anthony Brooks'],[],"{'description': 'Police in Vernal Heights, Flo...",http://themiamigazette.com/cannibals-arrested-...,...,{'$date': 1496151793000},http://themiamigazette.com,26.3405,25.694,232,232,1,7,1,1
220,[],[],[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],0,0,0
221,[],[],[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],0,0,0
226,226,227,PolitiFact_Fake_107,True,http://nativestuff.us/wp-content/uploads/2017/...,Australia Becomes First Country To Begin Micro...,[],[],"{'generator': 'WordPress 4.8', 'og': {'site_na...",http://nativestuff.us/2017/06/australia-become...,...,NaN,http://nativestuff.us,23.5217,25.0229,2969,2969,1,5,0,0
232,232,233,PolitiFact_Fake_113,True,http://teoinfo.com/wp-content/uploads/2017/06/...,"Fareed Zakaria, CNN host of ‘Foreign Affairs,’...",[],[],{'ca_image': 'http://teoinfo.com/wp-content/up...,http://teoinfo.com/2017/06/30/cnn-host-fareed-...,...,{'$date': 1498780800000},http://teoinfo.com,25.0675,22.5925,1200,1200,1,1,0,0

In [127]:

a = re.search(r"'published_tisme': '(.*)'},", str_1)
a?.group(1)

SyntaxError: invalid syntax (<ipython-input-127-74527753456b>, line 2)

In [156]:
newsUserContent[newsUserContent["publish_date"].isna()]

,Unnamed: 0,newsID,newsName,Fake,top_img,text,authors,keywords,meta_data,canonical_link,...,publish_date,source,avg No. of Followers,avg No. of Followees,PostIterations,Unique User count,shares/user,countImages,countAuthors,countKeywords
20,20,21,PolitiFact_Real_21,False,http://a.abcnews.com/images/Politics/gty_debat...,When Hillary Clinton attacked Donald Trump for...,"['Abc News', 'More Morgan']",[],"{'fb_title': 'Trump, Clinton Spar Over Taxes i...",http://abcnews.go.com/Politics/donald-trump-hi...,...,NaN,http://abcn.ws,22.9245,18.7736,53,53,1,4,2,2
23,23,24,PolitiFact_Real_24,False,http://s12.postimg.org/e9olv1lvx/article7.png,A Ukraine policewoman is dead after contractin...,[],[],"{'msapplication-TileColor': '#0e0e0e', 'news_k...",http://www.opposingviews.com/i/health/female-c...,...,NaN,http://www.opposingviews.com,12.75,15.3333,12,12,1,13,0,0
26,26,27,PolitiFact_Real_27,False,http://conservativetribune.com/wp-content/uplo...,McCain Criticized Trump for Arpaio’s Pardon… S...,[],[],"{'viewport': 'width=device-width, initial-scal...",NaN,...,NaN,http://conservativebyte.com,7.8,4.2,5,5,1,20,0,0
29,29,30,PolitiFact_Real_30,False,http://a.abcnews.com/images/Politics/RT_Trump_...,As Donald Trump courted African-American voter...,"['More Candace', 'Abc News']",[],{'fb_title': 'Trump Calls for Nationwide Stop-...,http://abcnews.go.com/Politics/donald-trump-ca...,...,NaN,http://abcn.ws,57.1633,52,49,49,1,4,2,2
36,36,37,PolitiFact_Real_37,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16081...,Washington Since we last updated the CNN battl...,"['Cnn Political Director', 'David Chalian']",[],{'description': 'CNN has updated its ratings o...,http://www.cnn.com/2016/09/22/politics/road-to...,...,NaN,http://cnn.it,23.9817,24.0745,873,873,1,3,2,2
37,37,38,PolitiFact_Real_38,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16091...,(CNN) North Korea went on the offensive Friday...,['Nicole Gaouette'],[],{'description': 'The US and Asian nations gath...,http://www.cnn.com/2016/09/22/politics/north-k...,...,NaN,http://cnn.it,11,2.875,8,8,1,63,1,1
40,40,41,PolitiFact_Real_41,False,http://a.abcnews.com/assets/beta/assets/abcn_i...,External links are provided for reference purp...,['Abc News'],[],"{'fb_title': 'ABC News', 'msApplication-ID': '...",http://abcnews.go.com,...,NaN,http://abcn.ws,46.1964,37.625,56,56,1,3,1,1
42,42,43,PolitiFact_Real_43,False,http://a.abcnews.com/images/International/ABC_...,"Nate Smith, executive director of the Texas Na...",['Abc News'],[],"{'fb_title': 'Texas, California Separatists At...",http://abcnews.go.com/International/texas-cali...,...,NaN,http://abcn.ws,18.76,17.08,25,25,1,5,1,1
46,46,47,PolitiFact_Real_47,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16072...,Story highlights Ivanka Trump will be attendin...,"['Deirdre Walsh', 'Cnn Senior Congressional Pr...",[],"{'description': ""Ivanka Trump will join female...",http://www.cnn.com/2016/09/20/politics/ivanka-...,...,NaN,http://cnn.it,18.2,16.4,5,5,1,2,2,2
47,47,48,PolitiFact_Real_48,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16030...,Story highlights Barney Frank says the tea par...,"['The Axe Files', 'Tim Skoczek']",[],{'description': 'He was one of the most effect...,http://www.cnn.com/2016/09/26/politics/barney-...,...,NaN,http://cnn.it,26.4536,22.0825,97,97,1,4,2,2
49,49,50,PolitiFact_Real_50,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16091...,Story highlights President Barack Obama said s...,['Caroline Kenny'],[],"{'description': ""President Barack Obama on Sun...",http://www.cnn.com/2016/09/18/politics/obama-s...,...,NaN,http://cnn.it,23.3571,22.6548,168,168,1,20,1,1
50,50,51,PolitiFact_Real_51,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16071...,Story highlights Michelle Obama was a guest on...,['David Wright'],[],{'description': 'Michelle Obama on Tuesday jok...,http://www.cnn.com/2016/09/21/politics/michell...,...,NaN,http://cnn.it,24.3243,23.6757,111,111,1,2,1,1
51,51,52,PolitiFact_Real_52,False,http://conservativetribune.com/wp-content/uplo...,McCain Criticized Trump for Arpaio’s Pardon… S...,[],[],"{'viewport': 'width=device-width, initial-scal...",NaN,...,NaN,http://conservativebyte.com,19.725,15.325,40,40,1,20,0,0
56,56,57,PolitiFact_Real_57,False,http://conservativetribune.com/wp-content/uplo...,McCain Criticized Trump for Arpaio’s Pardon… S...,[],[],"{'viewport': 'width=device-width, initial-scal...",NaN,...,NaN,http://conservativebyte.com,26.4643,22.75,28,28,1,20,0,0
58,58,59,PolitiFact_Real_59,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16092...,Story highlights Boy sent letter to Barack Oba...,['Claire Corkery'],[],{'description': 'A six-year-old boy has won th...,http://www.cnn.com/2016/09/22/politics/boys-le...,...,NaN,http://cnn.it,22.3753,20.6971,373,373,1,5,1,1
60,60,61,PolitiFact_Real_61,False,http://a.abcnews.com/images/Politics/ap_Congre...,"On Wednesday, the Senate is expected to overri...","['Abc News', 'More Ali']",[],"{'fb_title': ""How Congress Can Override Presid...",http://abcnews.go.com/Politics/congress-overri...,...,NaN,http://abcn.ws,24.5,20.5349,86,86,1,4,2,2
62,62,63,PolitiFact_Real_63,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16092...,Story highlights Famous golfer Arnold Palmer d...,['Allie Malloy'],[],{'description': 'President Barack Obama and Vi...,http://www.cnn.com/2016/09/26/politics/obama-b...,...,NaN,http://cnn.it,26.375,23.0417,24,24,1,3,1,1
64,64,65,PolitiFact_Real_65,False,http://i2.cdn.turner.com/money/dam/assets/1609...,Monday night was the most-watched debate in Am...,['Brian Stelter'],[],"{'news_keywords': 'Donald Trump, Hillary Clint...",http://money.cnn.com/2016/09/27/media/debate-r...,...,NaN,http://cnn.it,31.3289,30.7778,225,225,1,14,1,1
66,66,67,PolitiFact_Real_67,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16091...,Story highlights Stop-and-frisk is a type of a...,"['Steven A', 'Holmes Cnn']",[],"{'description': ""Donald Trump was asked by a m...",http://www.cnn.com/2016/09/22/politics/reality...,...,NaN,http://cnn.it,17.6026,13.0641,78,78,1,20,2,2
67,67,68,PolitiFact_Real_68,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16091...,Story highlights The tweet took center stage o...,['Phil Mattingly'],[],{'description': 'Donald Trump Jr. said Thursda...,http://www.cnn.com/2016/09/22/politics/donald-...,...,NaN,http://cnn.it,24.2775,22.4293,191,191,1,18,1,1
69,69,70,PolitiFact_Real_70,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16091...,Washington (CNN) Hillary Clinton is leading Do...,['Daniella Diaz'],[],{'description': 'Hillary Clinton is leading Do...,http://www.cnn.com/2016/09/21/politics/nbc-wsj...,...,NaN,http://cnn.it,25.7207,23.031,290,290,1,19,1,1
71,71,72,PolitiFact_Real_72,False,http://oppositionreport.com/wp-content/uploads...,\n\nPosted by John Prager on 20 Sep 2016\n\nTh...,[],[],"{'generator': 'WordPress 4.8.1', 'og': {'site_...",http://oppositionreport.com/twitter-just-wreck...,...,NaN,http://winningdemocrats.com,13.3636,7.63636,11,11,1,9,0,0
74,74,75,PolitiFact_Real_75,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/15111...,Story highlights Ahmad Khan Raham is alleged t...,"['Steve Vladeck', 'Cnn Contributor']",[],"{'description': ""The arrest of Ahmad Khan Raha...",http://www.cnn.com/2016/09/20/politics/legal-r...,...,NaN,http://cnn.it,38.8442,33.6753,77,77,1,28,2,2
76,76,77,PolitiFact_Real_77,False,http://a.abcnews.com/assets/beta/assets/abcn_i...,External links are provided for reference purp...,['Abc News'],[],"{'fb_title': 'ABC News', 'msApplication-ID': '...",http://abcnews.go.com,...,NaN,http://abcn.ws,4.6,0.8,5,5,1,3,1,1
77,77,78,PolitiFact_Real_78,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16072...,Story highlights House Speaker Paul Ryan and D...,"['Deirdre Walsh', 'Tal Kopan']",[],"{'description': ""Ivanka Trump, the Republican ...",http://www.cnn.com/2016/09/19/politics/ivanka-...,...,NaN,http://cnn.it,19.9086,16.3249,197,197,1,18,2,2
79,79,80,PolitiFact_Real_80,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/15092...,"Story highlights ""Transparent"" creator Jill So...",['David Wright'],[],{'description': 'One of the big winners at the...,http://www.cnn.com/2016/09/19/politics/jill-so...,...,NaN,http://cnn.it,19.6957,15.5652,46,46,1,123,1,1
80,80,81,PolitiFact_Real_81,False,http://a.abcnews.com/images/International/gty_...,A Syrian family leaves the area following a re...,['Abc News'],[],{'fb_title': 'Airstrikes Bury Syrians in Alepp...,http://abcnews.go.com/International/photos/air...,...,NaN,http://abcn.ws,9.6,11,5,5,1,7,1,1
87,87,88,PolitiFact_Real_88,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16092...,Story highlights Trump on Tuesday defended cal...,"['Manu Raju', 'Tom Lobianco', 'Deirdre Walsh']",[],"{'description': ""House Speaker Paul Ryan dodge...",http://www.cnn.com/2016/09/27/politics/paul-ry...,...,NaN,http://cnn.it,31.4808,27.5192,52,52,1,18,3,3
88,88,89,PolitiFact_Real_89,False,http://i2.cdn.turner.com/money/dam/assets/1609...,Donald Trump is turning to Snapchat to drum up...,['Hope King'],[],"{'news_keywords': 'Snapchat, Trump debate, Tru...",http://money.cnn.com/2016/09/26/technology/tru...,...,NaN,http://cnn.it,24.2737,21.7947,190,190,1,12,1,1
89,89,90,PolitiFact_Real_90,False,http://s13.postimg.org/4hyknud13/article8.png,An Ohio judge ordered an attorney jailed for f...,[],[],"{'msapplication-TileColor': '#0e0e0e', 'descri...",http://www.opposingviews.com/i/society/judge-t...,...,NaN,http://www.opposingviews.com,7.4,1.4,5,5,1,8,0,0
93,93,94,PolitiFact_Real_94,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16041...,New York (CNN) Hillary Clinton is visiting onl...,"['Jeff Zeleny', 'Dan Merica']",[],{'description': 'Hillary Clinton is visiting o...,http://www.cnn.com/2016/09/20/politics/hillary...,...,NaN,http://cnn.it,25.1975,22.6019,324,324,1,7,2,2
97,97,98,PolitiFact_Real_98,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16092...,Story highlights Trump was sitting in a chair ...,['Jeremy Diamond'],[],{'description': 'The controversial boxing prom...,http://www.cnn.com/2016/09/21/politics/don-kin...,...,NaN,http://cnn.it,18,12.9815,54,54,1,93,1,1
98,98,99,PolitiFact_Real_99,False,http://a.abcnews.com/images/Politics/AP_donald...,"Donald Trump Jr., a son of the Republican pres...",['Abc News'],[],{'fb_title': 'Trump Jr. Compares Syrian Refuge...,http://abcnews.go.com/Politics/donald-trump-jr...,...,NaN,http://abcn.ws,21.4182,15.3091,110,110,1,4,1,1
99,99,100,PolitiFact_Real_100,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16091...,Story highlights The House Oversight panel vot...,"['Tom Lobianco', 'Deirdre Walsh']",[],"{'description': ""Members of the House Oversigh...",http://www.cnn.com/2016/09/22/politics/bryan-p...,...,NaN,http://cnn.it,16.8361,97.2459,61,61,1,21,2,2
105,105,106,PolitiFact_Real_106,False,http://a.abcnews.com/images/Politics/AP_hofstr...,An anti-Donald Trump super PAC is going on the...,"['More Michael', 'Abc News']",[],{'fb_title': 'Anti-Trump Super PAC Launches Pr...,http://abcnews.go.com/Politics/anti-trump-supe...,...,NaN,http://abcn.ws,28.9651,35.9186,86,86,1,4,2,2
107,107,108,PolitiFact_Real_108,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16020...,"Story highlights ""I don't know how you could h...","['Eugene Scott', 'Daniella Diaz']",[],"{'description': ""New York Gov. Andrew Cuomo sa...",http://www.cnn.com/2016/09/19/politics/andrew-...,...,NaN,http://cnn.it,24.2552,20.069,145,145,1,3,2,2
108,108,109,PolitiFact_Real_109,False,http://i2.cdn.cnn.com/cnnnext/dam/assets/16091...,Story highlights Clinton is offering voters an...,['Dan Merica'],[],"{'description': ""Hillary Clinton's economic sp...",http://www.cnn.com/2016/09/20/politics/hillary...,...,NaN,http://cnn.it,6.6,4.8,5,5,1,21,1,1
143,143,144,PolitiFact_Fake_24,True,NaN,NaN,[],[],{'description': 'cnnews3.com is your first and...,NaN,...,NaN,http://cnnews3.com,21.8499,23.5242,393,393,1,1,0,0
158,158,159,PolitiFact_Fake_39,True,http://www.blackinsurancenews.com/wp-content/u...,By Free Wood Post\n\nHOUSTON — It seems new Na...,[],[],"{'keywords': '.,1,br,cbs,fl,inc,la,man,ny,obam...",http://www.blackinsurancenews.com/uncategorize...,...,NaN,http://www.blackinsurancenews.com,27.1515,24.1212,66,66,1,150,0,0
177,177,178,PolitiFact_Fake_58,True,http://www.neonnettle.com/videos/images/fronma...,Doctors Who Discovered Cancer Enzymes In Vacci...,"['Jack Murphy', 'Neon Nettle']",[],{'description': 'Doctors Who Discovered Cancer...,NaN,...,NaN,http://www.neonnettle.com,23.3379,21.9816,2548,2548,1,26,2,2
201,201,202,PolitiFact_Fake_82,True,http://static.lakana.com/media.fox5dc.com/phot...,Seth Rich Seth Rich\n\n- EDITOR'S NOTE (5/17/1...,[],[],"{'description': ""It has been almost a year sin...",http://www.fox5dc.com/news/local-news/25485233...,...,NaN,http://www.fox5dc.com,65.5,69,2,2,1,5,0,0
203,203,204,PolitiFact_Fake_84,True,http://thesolexchange.com/wp-content/uploads/2...,We all get lazy from time to time and just wan...,['Mr Hypebeast'],[],{'og': {'url': 'http://thesolexchange.com/nasa...,http://thesolexchange.com/nasa-will-pay-you-18...,...,NaN,http://thesolexchange.com,26.411,27.2745,601,601,1,449,1,1
209,209,210,PolitiFact_Fake_90,True,https://cdn2.hubspot.net/hubfs/2565357/trump%2...,"{% set baseFontFamily = ""Open Sans"" %} /* Add ...",['Jesse James'],[],{'description': 'Marines are finally getting t...,http://blog.veterantv.net/trump-removing-marin...,...,NaN,http://blog.veterantv.net,38.1429,32,7,7,1,14,1,1
211,211,212,PolitiFact_Fake_92,True,http://bestthings.us/wp-content/uploads/2017/0...,"Other than acting, Keanu’s wisdom towards life...",[],[],"{'og': {'site_name': 'The Best Things', 'descr...",http://bestthings.us/keanu-reeves-shock-the-wo...,...,NaN,http://bestthings.us,28.1,28.9,40,40,1,13,0,0
226,226,227,PolitiFact_Fake_107,True,http://nativestuff.us/wp-content/uploads/2017/...,Australia Becomes First Country To Begin Micro...,[],[],"{'generator': 'WordPress 4.8', 'og': {'site_na...",http://nativestuff.us/2017/06/australia-become...,...,NaN,http://nativestuff.us,23.5217,25.0229,2969,2969,1,5,0,0

SyntaxError: invalid syntax (<ipython-input-114-b84d299c9387>, line 1)

In [ ]:
import json
json.loads(str_1)

In [ ]:
newsUserContent.columns

In [ ]:
newsUserContent.loc[0, 'images'].count(',')+1

In [ ]:
userNewsInfo['newsID1']=  str(userNewsInfo['newsName'])
userNewsInfo['userID1']=  userNewsInfo['newsName'].to_string() + userNewsInfo['userID'].to_string()
userNewsInfo.head(2)

In [ ]:
userNewsInfo.loc[0, 'userID1']

In [ ]:
userNewsInfo.shape